version: '2.4'
services: 
  paperon-app:
    container_name: paperon-app
    image: wissmedia/paperon:1.1.0
    ports: 
      - "4500:8080"
    environment: 
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
      MONGO_HOSTNAME: paperon-db
      MONGO_PORT: 27017
      MONGO_DB: paperon
    restart: unless-stopped
    links: 
      - paperon-db
  paperon-db:
    container_name: paperon-db
    image: mongo:4.4.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - /appconfig/paperon/db_data:/data/db
    restart: unless-stopped